name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]
        include:
          - os: windows-latest
            target: x86_64-pc-windows-gnu

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        target: ${{ matrix.target }}
    
    - name: Install cargo-zigbuild
      if: matrix.target == 'x86_64-pc-windows-gnu'
      run: cargo install cargo-zigbuild

    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev libudev-dev pkg-config libdav1d-dev libc++-dev libc++abi-dev

    - name: Install system dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install dav1d


    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Run tests
      run: ${{ matrix.target == 'x86_64-pc-windows-gnu' && 'cargo zigbuild' || 'cargo' }} test --verbose ${{ matrix.target && format('--target {0}', matrix.target) || '' }}

    - name: Run clippy
      run: ${{ matrix.target == 'x86_64-pc-windows-gnu' && 'cargo zigbuild' || 'cargo' }} clippy ${{ matrix.target && format('--target {0}', matrix.target) || '' }} -- -D warnings

    - name: Check formatting
      run: cargo fmt --all -- --check

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]
        include:
          - os: windows-latest
            target: x86_64-pc-windows-gnu

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        target: ${{ matrix.target }}
    
    - name: Install cargo-zigbuild
      if: matrix.target == 'x86_64-pc-windows-gnu'
      run: cargo install cargo-zigbuild

    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev libudev-dev pkg-config libdav1d-dev libc++-dev libc++abi-dev

    - name: Install system dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install dav1d


    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-build-
          ${{ runner.os }}-cargo-

    - name: Build (debug)
      run: ${{ matrix.target == 'x86_64-pc-windows-gnu' && 'cargo zigbuild' || 'cargo' }} build --verbose ${{ matrix.target && format('--target {0}', matrix.target) || '' }}

    - name: Build (release)
      run: ${{ matrix.target == 'x86_64-pc-windows-gnu' && 'cargo zigbuild' || 'cargo' }} build --release --verbose ${{ matrix.target && format('--target {0}', matrix.target) || '' }}